
MY_COMPILER := /home/szakal/uc/setup-scripts/build/tmp-angstrom_2010_x-eglibc/sysroots/i686-linux/usr/bin/armv7a-angstrom-linux-gnueabi/arm-angstrom-linux-gnueabi-

MY_SOURCE := /home/szakal/uc/setup-scripts/build/tmp-angstrom_2010_x-eglibc/work/beaglebone-angstrom-linux-gnueabi/linux-ti33x-psp-3.1-r2f+gitr1d84d8853fa30cf3db2571a5aec572accca4e29d/git



